package model.entity;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 09 23:09:50 CEST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TradeFaireVisitorEOCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public TradeFaireVisitorEOCollImpl() {
    }
}

