package model.entity;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 09 23:09:49 CEST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TradeFaireVisitorEODefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TradeFaireVisitorEODefImpl() {
    }
}

