package model.view;

import java.util.HashMap;

import model.entity.TradeFaireVisitorEOImpl;

import model.view.common.TradeFaireVisitorVORow;

import oracle.jbo.domain.Array;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ProgrammaticViewRowImpl;
import oracle.jbo.server.ViewAttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 09 23:39:14 CEST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TradeFaireVisitorVORowImpl extends ProgrammaticViewRowImpl implements TradeFaireVisitorVORow {

    public static final int ENTITY_TRADEFAIREVISITOR = 0;

    /**
     * createRowData - for custom java data source support.
     * Overridden to initialize the dataProvier for newly created row.
     * Used for updateable View Objects.
     */
    public Object createRowData(HashMap attrNameValueMap) {
        Object value = super.createRowData(attrNameValueMap);
        return value;
    }

    /**
     * convertToSourceType - for custom java data source support.
     * Overridden to provide custom implementation for conversions of a value
     * from attribute java type to datasource column/field type.
     * Not required in most cases.
     */
    public Object convertToSourceType(ViewAttributeDefImpl attrDef, String sourceType, Object val) {
        Object value = super.convertToSourceType(attrDef, sourceType, val);
        return value;
    }

    /**
     * convertToAttributeType - for custom java data source support.
     * Overridden to provide custom implementation for conversions of a value
     *  from datasource/column field type to attribute java type.
     * Not required in most cases.
     */
    public Object convertToAttributeType(ViewAttributeDefImpl attrDef, Class javaTypeClass, Object val) {
        Object value = super.convertToAttributeType(attrDef, javaTypeClass, val);
        return value;
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        VisitorAmountOfExhibitorsToBeVisited,
        VisitorAmountOfExhibitorsToBeVisitedForPrivateMeetup,
        VisitorAmountOfExhibitorsToBeVisitedForPublicEvent,
        VisitorAppointmentsDuringWholeTradeFaire,
        VisitorBreakesList,
        VisitorEmail,
        VisitorFirstName,
        VisitorId,
        VisitorLastName,
        VisitorMainInterestsForTradeFaireExhibitors,
        VisitorNewContacts,
        VisitorNotesForExhibitors,
        VisitorPriotorizedMainInterests,
        VisitorPrivateAppointmentsDuringWholeTradeFaire,
        VisitorPublicEventsAppointmentsDuringWholeTradeFaire,
        VisitorRegistrationToTradeFair,
        VisitorRequestNotificationForFutureTradeFair,
        VisitorRequestsMoreInformationFromExhibitors,
        VisitorSpecificMoreOptionalInterests;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int VISITORAMOUNTOFEXHIBITORSTOBEVISITED =
        AttributesEnum.VisitorAmountOfExhibitorsToBeVisited.index();
    public static final int VISITORAMOUNTOFEXHIBITORSTOBEVISITEDFORPRIVATEMEETUP =
        AttributesEnum.VisitorAmountOfExhibitorsToBeVisitedForPrivateMeetup.index();
    public static final int VISITORAMOUNTOFEXHIBITORSTOBEVISITEDFORPUBLICEVENT =
        AttributesEnum.VisitorAmountOfExhibitorsToBeVisitedForPublicEvent.index();
    public static final int VISITORAPPOINTMENTSDURINGWHOLETRADEFAIRE =
        AttributesEnum.VisitorAppointmentsDuringWholeTradeFaire.index();
    public static final int VISITORBREAKESLIST = AttributesEnum.VisitorBreakesList.index();
    public static final int VISITOREMAIL = AttributesEnum.VisitorEmail.index();
    public static final int VISITORFIRSTNAME = AttributesEnum.VisitorFirstName.index();
    public static final int VISITORID = AttributesEnum.VisitorId.index();
    public static final int VISITORLASTNAME = AttributesEnum.VisitorLastName.index();
    public static final int VISITORMAININTERESTSFORTRADEFAIREEXHIBITORS =
        AttributesEnum.VisitorMainInterestsForTradeFaireExhibitors.index();
    public static final int VISITORNEWCONTACTS = AttributesEnum.VisitorNewContacts.index();
    public static final int VISITORNOTESFOREXHIBITORS = AttributesEnum.VisitorNotesForExhibitors.index();
    public static final int VISITORPRIOTORIZEDMAININTERESTS = AttributesEnum.VisitorPriotorizedMainInterests.index();
    public static final int VISITORPRIVATEAPPOINTMENTSDURINGWHOLETRADEFAIRE =
        AttributesEnum.VisitorPrivateAppointmentsDuringWholeTradeFaire.index();
    public static final int VISITORPUBLICEVENTSAPPOINTMENTSDURINGWHOLETRADEFAIRE =
        AttributesEnum.VisitorPublicEventsAppointmentsDuringWholeTradeFaire.index();
    public static final int VISITORREGISTRATIONTOTRADEFAIR = AttributesEnum.VisitorRegistrationToTradeFair.index();
    public static final int VISITORREQUESTNOTIFICATIONFORFUTURETRADEFAIR =
        AttributesEnum.VisitorRequestNotificationForFutureTradeFair.index();
    public static final int VISITORREQUESTSMOREINFORMATIONFROMEXHIBITORS =
        AttributesEnum.VisitorRequestsMoreInformationFromExhibitors.index();
    public static final int VISITORSPECIFICMOREOPTIONALINTERESTS =
        AttributesEnum.VisitorSpecificMoreOptionalInterests.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TradeFaireVisitorVORowImpl() {
    }

    /**
     * Gets TradeFaireVisitor entity object.
     * @return the TradeFaireVisitor
     */
    public TradeFaireVisitorEOImpl getTradeFaireVisitor() {
        return (TradeFaireVisitorEOImpl) getEntity(ENTITY_TRADEFAIREVISITOR);
    }

    /**
     * Gets the attribute value for VISITOR_AMOUNT_OF_EXHIBITORS_T using the alias name VisitorAmountOfExhibitorsToBeVisited.
     * @return the VISITOR_AMOUNT_OF_EXHIBITORS_T
     */
    public Integer getVisitorAmountOfExhibitorsToBeVisited() {
        return (Integer) getAttributeInternal(VISITORAMOUNTOFEXHIBITORSTOBEVISITED);
    }

    /**
     * Sets <code>value</code> as attribute value for VISITOR_AMOUNT_OF_EXHIBITORS_T using the alias name VisitorAmountOfExhibitorsToBeVisited.
     * @param value value to set the VISITOR_AMOUNT_OF_EXHIBITORS_T
     */
    public void setVisitorAmountOfExhibitorsToBeVisited(Integer value) {
        setAttributeInternal(VISITORAMOUNTOFEXHIBITORSTOBEVISITED, value);
    }

    /**
     * Gets the attribute value for VISITOR_AMOUNT_OF_EXHIBITORS_T using the alias name VisitorAmountOfExhibitorsToBeVisitedForPrivateMeetup.
     * @return the VISITOR_AMOUNT_OF_EXHIBITORS_T
     */
    public Integer getVisitorAmountOfExhibitorsToBeVisitedForPrivateMeetup() {
        return (Integer) getAttributeInternal(VISITORAMOUNTOFEXHIBITORSTOBEVISITEDFORPRIVATEMEETUP);
    }

    /**
     * Sets <code>value</code> as attribute value for VISITOR_AMOUNT_OF_EXHIBITORS_T using the alias name VisitorAmountOfExhibitorsToBeVisitedForPrivateMeetup.
     * @param value value to set the VISITOR_AMOUNT_OF_EXHIBITORS_T
     */
    public void setVisitorAmountOfExhibitorsToBeVisitedForPrivateMeetup(Integer value) {
        setAttributeInternal(VISITORAMOUNTOFEXHIBITORSTOBEVISITEDFORPRIVATEMEETUP, value);
    }

    /**
     * Gets the attribute value for VISITOR_AMOUNT_OF_EXHIBITORS_T using the alias name VisitorAmountOfExhibitorsToBeVisitedForPublicEvent.
     * @return the VISITOR_AMOUNT_OF_EXHIBITORS_T
     */
    public Integer getVisitorAmountOfExhibitorsToBeVisitedForPublicEvent() {
        return (Integer) getAttributeInternal(VISITORAMOUNTOFEXHIBITORSTOBEVISITEDFORPUBLICEVENT);
    }

    /**
     * Sets <code>value</code> as attribute value for VISITOR_AMOUNT_OF_EXHIBITORS_T using the alias name VisitorAmountOfExhibitorsToBeVisitedForPublicEvent.
     * @param value value to set the VISITOR_AMOUNT_OF_EXHIBITORS_T
     */
    public void setVisitorAmountOfExhibitorsToBeVisitedForPublicEvent(Integer value) {
        setAttributeInternal(VISITORAMOUNTOFEXHIBITORSTOBEVISITEDFORPUBLICEVENT, value);
    }

    /**
     * Gets the attribute value for VISITOR_APPOINTMENTS_DURING_WH using the alias name VisitorAppointmentsDuringWholeTradeFaire.
     * @return the VISITOR_APPOINTMENTS_DURING_WH
     */
    public Array getVisitorAppointmentsDuringWholeTradeFaire() {
        return (Array) getAttributeInternal(VISITORAPPOINTMENTSDURINGWHOLETRADEFAIRE);
    }

    /**
     * Sets <code>value</code> as attribute value for VISITOR_APPOINTMENTS_DURING_WH using the alias name VisitorAppointmentsDuringWholeTradeFaire.
     * @param value value to set the VISITOR_APPOINTMENTS_DURING_WH
     */
    public void setVisitorAppointmentsDuringWholeTradeFaire(Array value) {
        setAttributeInternal(VISITORAPPOINTMENTSDURINGWHOLETRADEFAIRE, value);
    }

    /**
     * Gets the attribute value for VISITOR_BREAKES_LIST using the alias name VisitorBreakesList.
     * @return the VISITOR_BREAKES_LIST
     */
    public Array getVisitorBreakesList() {
        return (Array) getAttributeInternal(VISITORBREAKESLIST);
    }

    /**
     * Sets <code>value</code> as attribute value for VISITOR_BREAKES_LIST using the alias name VisitorBreakesList.
     * @param value value to set the VISITOR_BREAKES_LIST
     */
    public void setVisitorBreakesList(Array value) {
        setAttributeInternal(VISITORBREAKESLIST, value);
    }

    /**
     * Gets the attribute value for VISITOR_EMAIL using the alias name VisitorEmail.
     * @return the VISITOR_EMAIL
     */
    public String getVisitorEmail() {
        return (String) getAttributeInternal(VISITOREMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for VISITOR_EMAIL using the alias name VisitorEmail.
     * @param value value to set the VISITOR_EMAIL
     */
    public void setVisitorEmail(String value) {
        setAttributeInternal(VISITOREMAIL, value);
    }

    /**
     * Gets the attribute value for VISITOR_FIRST_NAME using the alias name VisitorFirstName.
     * @return the VISITOR_FIRST_NAME
     */
    public String getVisitorFirstName() {
        return (String) getAttributeInternal(VISITORFIRSTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for VISITOR_FIRST_NAME using the alias name VisitorFirstName.
     * @param value value to set the VISITOR_FIRST_NAME
     */
    public void setVisitorFirstName(String value) {
        setAttributeInternal(VISITORFIRSTNAME, value);
    }

    /**
     * Gets the attribute value for VISITOR_ID using the alias name VisitorId.
     * @return the VISITOR_ID
     */
    public Integer getVisitorId() {
        return (Integer) getAttributeInternal(VISITORID);
    }

    /**
     * Sets <code>value</code> as attribute value for VISITOR_ID using the alias name VisitorId.
     * @param value value to set the VISITOR_ID
     */
    public void setVisitorId(Integer value) {
        setAttributeInternal(VISITORID, value);
    }

    /**
     * Gets the attribute value for VISITOR_LAST_NAME using the alias name VisitorLastName.
     * @return the VISITOR_LAST_NAME
     */
    public String getVisitorLastName() {
        return (String) getAttributeInternal(VISITORLASTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for VISITOR_LAST_NAME using the alias name VisitorLastName.
     * @param value value to set the VISITOR_LAST_NAME
     */
    public void setVisitorLastName(String value) {
        setAttributeInternal(VISITORLASTNAME, value);
    }

    /**
     * Gets the attribute value for VISITOR_MAIN_INTERESTS_FOR_TRA using the alias name VisitorMainInterestsForTradeFaireExhibitors.
     * @return the VISITOR_MAIN_INTERESTS_FOR_TRA
     */
    public Array getVisitorMainInterestsForTradeFaireExhibitors() {
        return (Array) getAttributeInternal(VISITORMAININTERESTSFORTRADEFAIREEXHIBITORS);
    }

    /**
     * Sets <code>value</code> as attribute value for VISITOR_MAIN_INTERESTS_FOR_TRA using the alias name VisitorMainInterestsForTradeFaireExhibitors.
     * @param value value to set the VISITOR_MAIN_INTERESTS_FOR_TRA
     */
    public void setVisitorMainInterestsForTradeFaireExhibitors(Array value) {
        setAttributeInternal(VISITORMAININTERESTSFORTRADEFAIREEXHIBITORS, value);
    }

    /**
     * Gets the attribute value for VISITOR_NEW_CONTACTS using the alias name VisitorNewContacts.
     * @return the VISITOR_NEW_CONTACTS
     */
    public Array getVisitorNewContacts() {
        return (Array) getAttributeInternal(VISITORNEWCONTACTS);
    }

    /**
     * Sets <code>value</code> as attribute value for VISITOR_NEW_CONTACTS using the alias name VisitorNewContacts.
     * @param value value to set the VISITOR_NEW_CONTACTS
     */
    public void setVisitorNewContacts(Array value) {
        setAttributeInternal(VISITORNEWCONTACTS, value);
    }

    /**
     * Gets the attribute value for VISITOR_NOTES_FOR_EXHIBITORS using the alias name VisitorNotesForExhibitors.
     * @return the VISITOR_NOTES_FOR_EXHIBITORS
     */
    public Array getVisitorNotesForExhibitors() {
        return (Array) getAttributeInternal(VISITORNOTESFOREXHIBITORS);
    }

    /**
     * Sets <code>value</code> as attribute value for VISITOR_NOTES_FOR_EXHIBITORS using the alias name VisitorNotesForExhibitors.
     * @param value value to set the VISITOR_NOTES_FOR_EXHIBITORS
     */
    public void setVisitorNotesForExhibitors(Array value) {
        setAttributeInternal(VISITORNOTESFOREXHIBITORS, value);
    }

    /**
     * Gets the attribute value for VISITOR_PRIOTORIZED_MAIN_INTER using the alias name VisitorPriotorizedMainInterests.
     * @return the VISITOR_PRIOTORIZED_MAIN_INTER
     */
    public Array getVisitorPriotorizedMainInterests() {
        return (Array) getAttributeInternal(VISITORPRIOTORIZEDMAININTERESTS);
    }

    /**
     * Sets <code>value</code> as attribute value for VISITOR_PRIOTORIZED_MAIN_INTER using the alias name VisitorPriotorizedMainInterests.
     * @param value value to set the VISITOR_PRIOTORIZED_MAIN_INTER
     */
    public void setVisitorPriotorizedMainInterests(Array value) {
        setAttributeInternal(VISITORPRIOTORIZEDMAININTERESTS, value);
    }

    /**
     * Gets the attribute value for VISITOR_PRIVATE_APPOINTMENTS_D using the alias name VisitorPrivateAppointmentsDuringWholeTradeFaire.
     * @return the VISITOR_PRIVATE_APPOINTMENTS_D
     */
    public Array getVisitorPrivateAppointmentsDuringWholeTradeFaire() {
        return (Array) getAttributeInternal(VISITORPRIVATEAPPOINTMENTSDURINGWHOLETRADEFAIRE);
    }

    /**
     * Sets <code>value</code> as attribute value for VISITOR_PRIVATE_APPOINTMENTS_D using the alias name VisitorPrivateAppointmentsDuringWholeTradeFaire.
     * @param value value to set the VISITOR_PRIVATE_APPOINTMENTS_D
     */
    public void setVisitorPrivateAppointmentsDuringWholeTradeFaire(Array value) {
        setAttributeInternal(VISITORPRIVATEAPPOINTMENTSDURINGWHOLETRADEFAIRE, value);
    }

    /**
     * Gets the attribute value for VISITOR_PUBLIC_EVENTS_APPOINTM using the alias name VisitorPublicEventsAppointmentsDuringWholeTradeFaire.
     * @return the VISITOR_PUBLIC_EVENTS_APPOINTM
     */
    public Array getVisitorPublicEventsAppointmentsDuringWholeTradeFaire() {
        return (Array) getAttributeInternal(VISITORPUBLICEVENTSAPPOINTMENTSDURINGWHOLETRADEFAIRE);
    }

    /**
     * Sets <code>value</code> as attribute value for VISITOR_PUBLIC_EVENTS_APPOINTM using the alias name VisitorPublicEventsAppointmentsDuringWholeTradeFaire.
     * @param value value to set the VISITOR_PUBLIC_EVENTS_APPOINTM
     */
    public void setVisitorPublicEventsAppointmentsDuringWholeTradeFaire(Array value) {
        setAttributeInternal(VISITORPUBLICEVENTSAPPOINTMENTSDURINGWHOLETRADEFAIRE, value);
    }

    /**
     * Gets the attribute value for VISITOR_REGISTRATION_TO_TRADE_ using the alias name VisitorRegistrationToTradeFair.
     * @return the VISITOR_REGISTRATION_TO_TRADE_
     */
    public Date getVisitorRegistrationToTradeFair() {
        return (Date) getAttributeInternal(VISITORREGISTRATIONTOTRADEFAIR);
    }

    /**
     * Sets <code>value</code> as attribute value for VISITOR_REGISTRATION_TO_TRADE_ using the alias name VisitorRegistrationToTradeFair.
     * @param value value to set the VISITOR_REGISTRATION_TO_TRADE_
     */
    public void setVisitorRegistrationToTradeFair(Date value) {
        setAttributeInternal(VISITORREGISTRATIONTOTRADEFAIR, value);
    }

    /**
     * Gets the attribute value for VISITOR_REQUEST_NOTIFICATION_F using the alias name VisitorRequestNotificationForFutureTradeFair.
     * @return the VISITOR_REQUEST_NOTIFICATION_F
     */
    public Boolean getVisitorRequestNotificationForFutureTradeFair() {
        return (Boolean) getAttributeInternal(VISITORREQUESTNOTIFICATIONFORFUTURETRADEFAIR);
    }

    /**
     * Sets <code>value</code> as attribute value for VISITOR_REQUEST_NOTIFICATION_F using the alias name VisitorRequestNotificationForFutureTradeFair.
     * @param value value to set the VISITOR_REQUEST_NOTIFICATION_F
     */
    public void setVisitorRequestNotificationForFutureTradeFair(Boolean value) {
        setAttributeInternal(VISITORREQUESTNOTIFICATIONFORFUTURETRADEFAIR, value);
    }

    /**
     * Gets the attribute value for VISITOR_REQUESTS_MORE_INFORMAT using the alias name VisitorRequestsMoreInformationFromExhibitors.
     * @return the VISITOR_REQUESTS_MORE_INFORMAT
     */
    public Array getVisitorRequestsMoreInformationFromExhibitors() {
        return (Array) getAttributeInternal(VISITORREQUESTSMOREINFORMATIONFROMEXHIBITORS);
    }

    /**
     * Sets <code>value</code> as attribute value for VISITOR_REQUESTS_MORE_INFORMAT using the alias name VisitorRequestsMoreInformationFromExhibitors.
     * @param value value to set the VISITOR_REQUESTS_MORE_INFORMAT
     */
    public void setVisitorRequestsMoreInformationFromExhibitors(Array value) {
        setAttributeInternal(VISITORREQUESTSMOREINFORMATIONFROMEXHIBITORS, value);
    }

    /**
     * Gets the attribute value for VISITOR_SPECIFIC_MORE_OPTIONAL using the alias name VisitorSpecificMoreOptionalInterests.
     * @return the VISITOR_SPECIFIC_MORE_OPTIONAL
     */
    public Array getVisitorSpecificMoreOptionalInterests() {
        return (Array) getAttributeInternal(VISITORSPECIFICMOREOPTIONALINTERESTS);
    }

    /**
     * Sets <code>value</code> as attribute value for VISITOR_SPECIFIC_MORE_OPTIONAL using the alias name VisitorSpecificMoreOptionalInterests.
     * @param value value to set the VISITOR_SPECIFIC_MORE_OPTIONAL
     */
    public void setVisitorSpecificMoreOptionalInterests(Array value) {
        setAttributeInternal(VISITORSPECIFICMOREOPTIONALINTERESTS, value);
    }
}

