package model.view.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Array;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 09 23:39:28 CEST 2019
// ---------------------------------------------------------------------
public interface TradeFaireVisitorVORow extends Row {
    Integer getVisitorAmountOfExhibitorsToBeVisited();

    void setVisitorAmountOfExhibitorsToBeVisited(Integer value);

    Integer getVisitorAmountOfExhibitorsToBeVisitedForPrivateMeetup();

    void setVisitorAmountOfExhibitorsToBeVisitedForPrivateMeetup(Integer value);

    Integer getVisitorAmountOfExhibitorsToBeVisitedForPublicEvent();

    void setVisitorAmountOfExhibitorsToBeVisitedForPublicEvent(Integer value);

    Array getVisitorAppointmentsDuringWholeTradeFaire();

    void setVisitorAppointmentsDuringWholeTradeFaire(Array value);

    Array getVisitorBreakesList();

    void setVisitorBreakesList(Array value);

    String getVisitorEmail();

    void setVisitorEmail(String value);

    String getVisitorFirstName();

    void setVisitorFirstName(String value);

    Integer getVisitorId();

    void setVisitorId(Integer value);

    String getVisitorLastName();

    void setVisitorLastName(String value);

    Array getVisitorMainInterestsForTradeFaireExhibitors();

    void setVisitorMainInterestsForTradeFaireExhibitors(Array value);

    Array getVisitorNewContacts();

    void setVisitorNewContacts(Array value);

    Array getVisitorNotesForExhibitors();

    void setVisitorNotesForExhibitors(Array value);

    Array getVisitorPriotorizedMainInterests();

    void setVisitorPriotorizedMainInterests(Array value);

    Array getVisitorPrivateAppointmentsDuringWholeTradeFaire();

    void setVisitorPrivateAppointmentsDuringWholeTradeFaire(Array value);

    Array getVisitorPublicEventsAppointmentsDuringWholeTradeFaire();

    void setVisitorPublicEventsAppointmentsDuringWholeTradeFaire(Array value);

    Date getVisitorRegistrationToTradeFair();

    void setVisitorRegistrationToTradeFair(Date value);

    Boolean getVisitorRequestNotificationForFutureTradeFair();

    void setVisitorRequestNotificationForFutureTradeFair(Boolean value);

    Array getVisitorRequestsMoreInformationFromExhibitors();

    void setVisitorRequestsMoreInformationFromExhibitors(Array value);

    Array getVisitorSpecificMoreOptionalInterests();

    void setVisitorSpecificMoreOptionalInterests(Array value);
}

